# Generated by Django 3.2.8 on 2021-10-12 03:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import payments.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=64)),
                ('slug', models.SlugField(unique=True)),
                ('CNPJ', models.CharField(max_length=14, validators=[payments.models.only_int])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=64)),
                ('slug', models.SlugField(unique=True)),
                ('CNPJ', models.CharField(max_length=14, validators=[payments.models.only_int])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('issue_date', models.DateField()),
                ('due_date', models.DateField()),
                ('original_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.IntegerField(choices=[(0, 'unrequested'), (1, 'in progress'), (2, 'canceled'), (3, 'aproved')], default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.company')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.supplier')),
            ],
        ),
    ]
