version: "3.3"

services:
  database:
    image: postgres:9.6.0
    restart: always
    volumes:
      - ../pgdata:/var/lib/postgresql/data
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_PASSWORD=advpay
      - POSTGRES_USER=advpay
    ports:
      - 5432:5432

#   redis:
#     image: redis
#     ports:
#       - 6379:6379
